### ISSUE TITLE
No highlighting for @layer

### ISSUE THREAD

**Issue by brachkow** [SublimeText/Sass#102]
No highlighting for [@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) at-rule.

As it has [wide browser support](https://caniuse.com/mdn-css_at-rules_layer) and [used by tailwind](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer) — support is really needed.

**Comment by braver** [comment]
This is covered by #96, we’re mostly waiting for a stable ST4 release before finalizing that PR and releasing a new version. If you want you can already manually install that branch.

**Comment by braver** [comment]
closed via #96
