### ISSUE TITLE
Add support for container at-rule

### ISSUE THREAD

**Issue by amdd-tim** [SublimeText/Sass#103]
Sublime's official default CSS sytanx now includes support for the container at-rule ([https://github.com/sublimehq/Packages/pull/3819](https://github.com/sublimehq/Packages/pull/3819)). Will you be supporting that as well?

**Comment by braver** [comment]
Certainly! There is a lot of rewriting to be done though (working on it!), so not sure about the timeline.

**Comment by amdd-tim** [comment]
Dope. I'm sure there is. Looking forward to the updates.

**Comment by braver** [comment]
closed via #96
