### ISSUE TITLE
Detach fork

### ISSUE THREAD

**Issue by braver** [SublimeText/Sass#104]
It's possible to detach the fork relation through interaction with the support bot. However, that requires admin access to this repo, which I no longer have. @deathaxe maybe you can do this, or give me some more access to the repo so I can do it myself.

https://support.github.com/contact?tags=rr-forks&subject=Detach%20Fork&flow=detach_fork

**Comment by deathaxe** [comment]
Stubid chatbots!

Have gone along the way requesting detaching this fork and overtaking all childs. Let's see what happens.

Btw. You should have full access to this repo again.

**Comment by braver** [comment]
Thanks! 

You used to have to play this via an email to support… maybe the chatbot is easier? Always found it a bit weird that detaching forks is hard. Anyway, we’ll see what happens.

**Comment by deathaxe** [comment]
Well, yes. I wasn't aware of it being possible at all.

**Comment by braver** [comment]
I’ve done it before… 

which reminds me that we still want to do the same for the Terminal repo (which is forked from wbond’s original)

**Comment by braver** [comment]
Seems like the detachment has been processed ✅
