### ISSUE TITLE
Autocomplete stops working before a nested selector

### ISSUE THREAD

**Issue by ohboylan** [SublimeText/Sass#107]
When adding a new css property to the end of a property list, autocomplete stops working if there's a nested selector immediately following the new property. The type of nested selector doesn't seem to matter, it could be an `&`, a mixin, class, etc.

Tested in Windows and MacOS on the current stable build of ST4. Also tested in a clean install with only the Sass package installed with the same results.

Here's an example of autocomplete not working:
![1-autocomplete-not-working](https://github.com/SublimeText/Sass/assets/119971715/c35a04f5-f845-4139-9eaa-e83e82d16cab)

And here's an example of autocomplete working as normal, when adding a property to the top of the list:
![2-autocomplete-working](https://github.com/SublimeText/Sass/assets/119971715/5cc069e8-5a64-4140-bf75-33193a204633)

**Comment by deathaxe** [comment]
Syntactically `border-` is scoped as custom tag and thus part of the selector, which `h2` belongs to, too.

That's how nested CSS works, syntactically.

Properties are not suggested via auto-completions, within selectors.

That's working as expected.

**Comment by ohboylan** [comment]
That's absolutely correct, I can see Stylelint processing it as a selector instead of a property. However, when writing scss, I would expect it to be handled as a property. Having to add properties between existing ones in order to use autocomplete feels clunky.

If anyone else is running this issue - I've switched to LSP-css autocomplete for now, as they work as I would expect.

**Comment by deathaxe** [comment]
Maybe removing `meta.selector` restriction is enough. Let's try to suggest properties, everywhere.
