### ISSUE TITLE
Autocompletion of @mixin, @include, and mixin names

### ISSUE THREAD

**Issue by thie1210** [SublimeText/Sass#84]
I’m using ST4 with SublimeSass and Emmet, I can’t get autocompletion of the @mixin (=), @include (+) keywords as well as the name of my mixins. I use .sass files, but it doesn’t work with .scss files either.

**Comment by braver** [comment]
In #96 we can finally address this:

<img width="321" alt="Scherm­afbeelding 2024-02-26 om 21 45 05" src="https://github.com/braver/Sass/assets/2543659/cae81a04-33a0-4cfb-8212-7a3bd80671e6">
