### ISSUE TITLE
Beta 3.0: first-of-type, last-of-type; nth-child... not auto-completed anymore

### ISSUE THREAD

**Issue by artik** [SublimeText/Sass#89]
`first-of-type`, `last-of-type`; `nth-child`... not auto-completed anymore (and maybe some others):

![Peek 2022-01-19 21-29](https://user-images.githubusercontent.com/1015856/150209026-fa6825ce-895e-4a31-9845-1aea4eefa434.gif)

**Comment by braver** [comment]
That's correct, we don't offer completions for selectors. We never did that before, and neither does the default CSS package (unless I'm missing something).

**Comment by braver** [comment]
closed via #96
