### ISSUE TITLE
Missing syntax highlighting

### ISSUE THREAD

**Issue by spartie17** [SublimeText/Sass#93]
Hi there, I'm experiencing some weird syntax highlighting that seems to have appeared quite recently. The minus sign (-) is now highlighted, and px and the % sign used to be pink. I'm using version 2.5.4

What it currently looks like:
<img width="442" alt="Screenshot 2022-03-22 at 11 56 03AM@2x" src="https://user-images.githubusercontent.com/8684887/159387161-36b73f7a-c279-418c-9622-5f114dca44e5.png">

What it used to look like:
<img width="379" alt="Screenshot 2022-03-22 at 12 15 05PM@2x" src="https://user-images.githubusercontent.com/8684887/159388163-63748298-421b-4fda-a6c1-f428fc8d33cf.png">

**Comment by braver** [comment]
2.5.4 hasn’t been updated in ages. Can you try to upgrade to the 3.0 version (see the readme on how to do so)?

**Comment by spartie17** [comment]
It was the first thing I tried to do, but not having much luck with that either. I've added the prerelease code to the package control settings and then tried to upgrade packages, but it still says 2.5.4 is up-to-date. I'm running sublime build 4126 - is it because I'm using sublime 4?

<img width="285" alt="Screenshot 2022-03-22 at 05 14 47PM@2x" src="https://user-images.githubusercontent.com/8684887/159420032-ed71f516-9b9a-4414-bda2-3483b7e09413.png">

**Comment by braver** [comment]
No that should work in theory, although maybe a recent change in the release strategy might conflict here… Sass 3.0 is available for the most recent beta/dev builds of ST4 just to gently stagger the release. You could try out the latest dev build just to see what it does (although they’re usually stable enough to be a daily driver).

Is this a recent problem you’re having? It has really been a very long time since I worked on pre-3.0 if this package.

**Comment by spartie17** [comment]
Yep! Super recent, it only arose in the past week or so.

Installing the latest dev build seemed to force the package to update to v3, hooray! This has removed the highlight on the minus sign, but it's still a different colour to what it used to be along with px and %, and with v3 the mixin parameter has changed colour also. Not a huge deal - it all still works as it should and the main issue was the minus highlight. I've just grown so used to the previous colours that it would be awesome to have them back (:

Currently:
<img width="362" alt="Screenshot 2022-03-22 at 07 02 47PM@2x" src="https://user-images.githubusercontent.com/8684887/159434806-d0943174-b642-44a8-8c2e-014799e1983f.png">

Previously:
<img width="389" alt="Screenshot 2022-03-22 at 07 01 55PM@2x" src="https://user-images.githubusercontent.com/8684887/159434841-81a910fd-6c73-4d0e-b18b-2c1004cf7cae.png">

**Comment by braver** [comment]
Yes some changes, especially around units, are to be expected. This now aligns with the default CSS package (just try to write something similar in plain CSS, it should match).

I do wonder if I did something to create problems in 2.5.4 🤔 maybe once 3.0 trickles through to more users and I get the feedback that it’s ok, I could push it out to all ST4 users (or that happens organically when a new stable release happens)… I’ll keep an eye on it.

**Comment by akruit** [comment]
Bij seeing this, I have no highlighting at all when I using sass. I tried the latest dev build of Sublime today, but it is not working.  I work on a Mac

Dev Channel, Build 4129

Sass
Sass and SCSS syntax for Sublime Text
v3.0.0; packagecontrol.io/packages/Sass

**Comment by braver** [comment]
closed via #96
